### ISSUE TITLE
Incorrect capitalisation in breadcrumbs

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/creativecommons.github.io-source#472]
## Description
Acronym capitalisation in breadcrumbs are not handled correctly. There should be a better way to do this (or in the very least hardcode 'CC').

## Reproduction
1. Visit https://opensource.creativecommons.org/cc-search/
2. See error.

## Expectation
Expected to see 'CC', not 'Cc'.

## Screenshots
<img width="122" alt="Screenshot 2020-08-22 at 9 53 47 AM" src="https://user-images.githubusercontent.com/16580576/90948534-7db00300-e45d-11ea-802a-3b4234b9f3fd.png">

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by kgodey** [comment]
I think the best solution here would be to use the page titles (without altering the case) for the breadcrumbs, rather than the URLs.

**Comment by Aakash2408** [comment]
@kgodey I cant understand this can you please elaborate it a bit.

**Comment by Dhruvi16** [comment]
Hey @Aakash2408 for now we are extracting the URL for building content for the Breadcrumb component on every page. You will find the breadcrumb component in the [layout.html](https://github.com/creativecommons/creativecommons.github.io-source/blob/master/themes/vocabulary_theme/templates/layout.html) template with a `Breadcrumb` comment over it. So Kriti is suggesting that instead of extracting paths we use title blocks of the pages so there is no need for altering cases.

If it is still not clear lemme know.

**Comment by Aakash2408** [comment]
OK i will try it :)

**Comment by Aakash2408** [comment]
This is the part of code I need to change I guess
![Screenshot from 2020-09-01 13-17-13](https://user-images.githubusercontent.com/47134609/91822473-7eaf1480-ec55-11ea-822f-a0044a42844a.png)

**Comment by dhruvkb** [comment]
@Aakash2408 your screenshot is broken. You can [open a draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) if you want reviews on the changes you have made.

**Comment by tushar912** [comment]
can i work on this ?

**Comment by dhruvkb** [comment]
Yes @tushar912, please feel free to.
